# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
- task: Npm@1
  inputs:
    command: 'install'
    become: yes
    become_user: ubuntu
    become_method: sudo
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build-prod'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'